name: Build Push Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -t gcr.io/alank-first-project/todo-service .
    - name: Deploy service to Cloud Run
      uses: stefda/action-cloud-run@1.0.0
      with:
        image: gcr.io/alank-first-project/todo-service
        service: todo-service
        project: alank-first-project
        region: us-east1
        service key: ${{ secrets.GCP_AUTH }}