name: Build Push Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: todo-service
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build docker image
      run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME .

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.RUN_SA_EMAIL }}
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
    # - name: Deploy service to Cloud Run
    #   uses: stefda/action-cloud-run@v1.0
    #   with:
    #     image: gcr.io/alank-first-project/todo-service
    #     service: todo-service
    #     project: alank-first-project
    #     region: us-east1
    #     service key: ${{ secrets.GCP_AUTH }}