name: Build Push Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: alank-first-project
  # PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: todo-service
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build docker image
      run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.RUN_SA_EMAIL }}
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
    - name: configure docker to use GCR
      run: gcloud auth configure-docker
    - name: push image to GCR
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
    - name: deploy to Google Cloud Run
      run: gcloud run deploy --region us-central1 --image gcr.io/$PROJECT-ID/$SERVICE_NAME:$GITHUB_SHA --platform managed
